### ISSUE TITLE
Somehow modify ac-tmux-complete--in-tmux-p to work with emacsclient

### ISSUE THREAD

**Issue by glynnforrest** [syohex/emacs-ac-tmux-complete#1]
Thank you so much for this plugin! It's already saved me so much typing.

`ac-tmux-complete--in-tmux-p` doesn't work for me when I use emacsclient and the server has been started with the gui.

Steps to reproduce:
- Open gui emacs with server mode
- Start a tmux session and launch emacsclient
- Run `(ac-tmux-complete-ac-setup)`
- Try to autocomplete something
- Error - "Not running in tmux!!"

Obviously the error is because `getenv` uses the environment from the server process (the gui emacs) so no TMUX_PANE environment variable is set. Is there another way to detect if emacs is inside tmux so it would work with emacsclient too??

Thanks!

**Comment by syohex** [comment]
I see, but it is difficult to detect whether here is in `tmux` in such case.

``` patch
diff --git a/ac-tmux-complete.el b/ac-tmux-complete.el
index b8afc12..72ea3e3 100644
--- a/ac-tmux-complete.el
+++ b/ac-tmux-complete.el
@@ -24,11 +24,16 @@

 ;;; Code:

+(eval-when-compile
+  (defvar server-buffer-clients))
+
 (require 'cl-lib)
 (require 'auto-complete)

 (defsubst ac-tmux-complete--in-tmux-p ()
-  (getenv "TMUX_PANE"))
+  (or (getenv "TMUX_PANE")
+      ;; I believe here is in tmux if this emacs is 'emacsclient --tty'.
+      (and (featurep 'server) (not window-system) server-buffer-clients)))

 (defun ac-tmux-complete--collect-panes ()
   (with-temp-buffer

```

I try to consider about this.

**Comment by glynnforrest** [comment]
Thank you for looking into this - I'm going to have a think about it too.

**Comment by xorian** [comment]
Maybe you could put something in your tmux.conf to connect an existing to emacs to tmux when tmux starts.  Something like this:

`run-shell 'emacsclient --eval "(setenv \"TMUX\" \"$TMUX\")" > /dev/null'`

It might also make more sense for ac-tmux-complete--in-tmux-p to test for the TMUX environment variable rather than TMUX_PANE.

**Comment by syohex** [comment]
> It might also make more sense for ac-tmux-complete--in-tmux-p to test for the TMUX environment variable rather than TMUX_PANE.

I have updated. Thanks
